[chore]
label = "Chore ğŸ¤–"
description = "Build process or auxiliary tool changes"
vars = ["title"]
title = "chore ğŸ¤–: {{title}}"
branch_pattern = "^chore/.*"
body = """
# Description
"""

[ci]
label = "CI ğŸ¤–"
description = "CI related changes"
vars = ["title"]
title = "ci ğŸ¤–: {{title}}"
branch_pattern = "^ci/.*"
body = """
# Description
"""

[docs]
label = "Docs âœï¸"
description = "Documentation only changes"
vars = ["title"]
title = "docs âœï¸: {{title}}"
branch_pattern = "^docs/.*"
body = """
# Description
"""

[feat]
label = "Feat ğŸ¸"
description = "A new feature"
vars = ["title", "ticket"]
title = "feat ğŸ¸: {{title}}"
branch_pattern = "^feature/GP-{{ticket}}$"
body = """
# Description

\\## Breaking changes

**Closes [GP-{{ticket}}](https://connectnodes.atlassian.net/browse/GP-{{ticket}})**

# Depends on #XX
"""

[fix]
label = "Fix ğŸ"
description = "A bug fix"
vars = ["title", "ticket"]
title = "fix ğŸ: {{title}}"
branch_pattern = "^fix/GP-{{ticket}}$"
body = """
# Description

**Closes [GP-{{ticket}}](https://connectnodes.atlassian.net/browse/GP-{{ticket}})**

# Depends on #XX
"""

[perf]
label = "Perf âš¡ï¸"
description = "A code change that improves performance"
vars = ["title"]
title = "perf âš¡ï¸: {{title}}"
branch_pattern = "^perf/.*"
body = """
# Description
"""

[refactor]
label = "Refactor ğŸ’¡"
description = "A code change that neither fixes a bug or adds a feature"
vars = ["title"]
title = "refactor ğŸ’¡: {{title}}"
branch_pattern = "^refactor/.*"
body = """
# Description
"""

[release]
label = "Release ğŸ¹"
description = "Create a release commit"
vars = ["title"]
title = "release ğŸ¹: {{title}}"
branch_pattern = "^release/.*"
body = """
# Description
"""

[style]
label = "Style ğŸ’„"
description = "Markup, white-space, formatting, missing semi-colons..."
vars = ["title"]
title = "style ğŸ’„: {{title}}"
branch_pattern = "^style/.*"
body = """
# Description
"""

[test]
label = "Test ğŸ’"
description = "Adding missing tests"
vars = ["title"]
title = "test ğŸ’: {{title}}"
branch_pattern = "^test/.*"
body = """
# Description
"""
